# Scraping configuration
  # 1 for single-level, 
  # 2 for two-level scraping, 
  # 3 if you already have level 1 data, and want to get the details from each link
level: 1
url_file: urls.yml # this is the file that contains the urls to scrape

# AgentQL Query for Level 1 scraping look at how to make queries here: https://docs.agentql.com/quick-start
# if the name of "events" and prompt from level2_prompt is referencing something else, like "clubs", 
# then you need to change the name of "clubs" to "events"
# I use clubs when scraping data from clubs websites, events when scraping data from events websites
level1_query: """
{
    events[] {
        Name (name of the event)
        URL (url link for the event)
    }
}
"""
# NLP prompt for Level 2 scraping (using ScrapeGraph)
# level2_prompt for clubs:
# level2_prompt: "Extract the following information: club name, description, all social media links (Instagram, Facebook), phone number,and email address. Format as a JSON object."   

# level2_prompt for events:
level2_prompt: "Extract the event's title, description, date, location."